# Generated by Django 5.2.7 on 2025-11-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status_notified',
            field=models.BooleanField(default=True),
        ),
    ]
